# Generated by Django 5.1.2 on 2024-10-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('equipo', models.CharField(max_length=100)),
                ('tipo_sangre', models.CharField(max_length=3)),
                ('alegria', models.CharField(max_length=10)),
                ('pista', models.CharField(max_length=10)),
                ('tiempo_inicio', models.DateTimeField(blank=True, null=True)),
                ('tiempo_fin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
