# Generated by Django 5.1.2 on 2024-10-20 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicion', '0002_rename_alegria_competidor_alergia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posicion', models.IntegerField()),
                ('competidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competicion.competidor')),
            ],
        ),
    ]
